### ISSUE TITLE
About the method of evaluation

### ISSUE THREAD

**Issue by altfrog** [LJacksonPan/RaTrack#10]
First, it's a nice work!
And I would like to know how to get the index such as "AMOTA" shown in paper, since when I ran "python main.py --config configs_eval.yaml" only got the result: 
{'acc': 0.665439362981125, 'miou': 0.3327195646320973, 'sen': 0.5}
{'rne': 0.14621314785850364, '50-50 rne': nan, 'mov_rne': 0.0, 'stat_rne': nan, 'sas': 0.9976320735841153, 'ras': 0.9998527087334035, 'epe': 0.34478783385957384}.
Is there any other evaluate scripts didn't uploaded? Thanks!

**Comment by MrTooOldDriver** [comment]
Hi. Thank you for your interest in our work. The metrics you saw are just debugging metrics for the scene flow and motion segmentation module. Regarding the evaluation script, we have stated it in the README Q&A:

> Q: Regarding Our Modified AB3DMOT Evaluation Code
> A: Due to AB3DMOT's repository license, we are currently not able to distribute our modified version of the AB3DMOT evaluation. We are contacting AB3DMOT's authors to gain permission for distribution.

We are still working on gaining permission from them.
