### ISSUE TITLE
Is there any code that can input the detection result and get the tracking result of AB3DMOT model directly？

### ISSUE THREAD

**Issue by mojingyue521** [LJacksonPan/RaTrack#5]
Hello,  I want to use the val detection result of vod dataset as input to get the tracking result of AB3DMOT model. But due to the differences between the vod and kitti datasets, I'm not sure how the pose in the vod dataset fits into the oxts in the kitti dataset. Is there any code in your model RaTrack that can directly view AB3DMOT model results?

Looking forward to your reply, thank you

**Comment by MrTooOldDriver** [comment]
Hi, thank you for your question. I am not sure what you mean by "directly view AB3DMOT model results". However, I presume you are asking about how to use the VoD detection label in AB3DMOT. Unfortunately there is no code available in this codebase that allows you to directly load the VoD detection label in AB3DMOT. However I can provide some guidance on how to handle pose data.

The OXTS data in the KITTI dataset provides you with a series of transformations, which are equivalent to frame transformations in the VoD dataset. In RaTrack, we use the VoD development kit to obtain the transformation for calculating the ego pose. You could double check our code to see how we load and calculate the transformation. It should be useful for your purpose.

Additionally, I recommend you check out the notebook in the VoD repo: [2_frame_transformations.ipynb](https://github.com/tudelft-iv/view-of-delft-dataset/blob/main/2_frame_transformations.ipynb)

**Comment by mojingyue521** [comment]
thank you!
