### ISSUE TITLE
Backpropagation Through DBSCAN

### ISSUE THREAD

**Issue by M-Hammod** [LJacksonPan/RaTrack#7]
Thank you so much for sharing your work, it's awesome,  Could you please help me understand how the backpropegation through DBSCAN works?

**Comment by MrTooOldDriver** [comment]
Thank you for your reply.

DBSCAN isn't differentiable, hence backpropagation doesn't apply directly to DBSCAN. It is one of the improvements that could be applied to RaTrack by replacing DBSCAN with differentiable clustering.
